controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource: ../src/Controller/
    prefix: /api
    type: attribute

api_login_check:
    path: /api/login_check
